[build]
command = "npm test && npm run build"
functions = "netlify/functions"
publish = "build"

[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"
VITE_MT_EDIT_BUTTONS_ENABLED = false

[[plugins]]
package = "netlify-plugin-cypress"
[plugins.inputs.preBuild]
enable = true
start = "npm start"
wait-on = "http://localhost:3000"
wait-on-timeout = 30

## Uncomment to use this redirect for Single Page Applications like create-react-app.
## Not needed for static site generators.
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200

## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
#[dev]
#  command = "yarn start" # Command to start your dev server
#  port = 3000 # Port that the dev server will be listening on
#  publish = "dist" # Folder with the static content for _redirect file

## more info on configuring this file: https://ntl.fyi/file-based-build-config
