[build]
command = "npm test && npm run build"
functions = "netlify/functions"
publish = "build"
ignore = "./netlify-ignore.sh"

[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"
VITE_MT_EDIT_BUTTONS_ENABLED = "true"
VITE_BUILD = "$COMMIT_REF"

[[plugins]]
package = "netlify-plugin-cypress"
[plugins.inputs.preBuild]
enable = true
start = "npm start"
wait-on = "http://localhost:3000"
wait-on-timeout = 30

[[plugins]]
package = "@netlify/plugin-lighthouse"
