
[build]
command = "npm test && export VITE_BUILD=$COMMIT_REF && npm run build"
functions = "netlify/functions"
publish = "build"
ignore = "./netlify-ignore.sh"

[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"
VITE_MT_EDIT_BUTTONS_ENABLED = "true"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[plugins]]
package = "netlify-plugin-cypress"
[plugins.inputs.preBuild]
enable = true
start = "npm start"
wait-on = "http://localhost:3000"
wait-on-timeout = 30

[[plugins]]
package = "@netlify/plugin-lighthouse"

[plugins.inputs]
fail_deploy_on_score_thresholds = "true"
output_path = "reports/lighthouse.html"
[plugins.inputs.thresholds]
    performance = 0.5
    accessibility = 0.9
    "best-practices" = 0.9
    seo = 0.9
    pwa = 0.9

[[plugins]]
package = "./netlify/plugins/lighthouse-badge-generator"
