Resources:
  WebApp:
    Type: AndyToddDev::Stack::WebApp::MODULE
    Properties:
      AppDomain: wellness.andytodd.dev
      S3BucketName: wellness-bucket
      StagingCName: andy-todd-dev.github.io
