AWSTemplateFormatVersion: 2010-09-09

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: wellness-ui
      WebsiteConfiguration:
        ErrorDocument: "index.html"
        IndexDocument: "index.html"
  ReadPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action: "s3:GetObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal: "*"

  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "andytodd.dev"
  ZoneRecords:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneId:
        Ref: HostedZone
      RecordSets:
        - Type: A
          Name: "wellness.andytodd.dev"
          AliasTarget:
            HostedZoneId: "Z2FDTNDATAQYW2"
            DNSName:
              "Fn::GetAtt": ["CloudFrontDistribution", "DomainName"]

  ACMCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: wellness.andytodd.dev
      DomainValidationOptions:
        - DomainName: wellness.andytodd.dev
          HostedZoneId:
            Ref: HostedZone
      ValidationMethod: DNS

  # Configure Access to CloudFront
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref S3Bucket

  # Configure CloudFront
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - "wellness.andytodd.dev"
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn:
            Ref: ACMCertificate
        CustomErrorResponses:
          - ErrorCode: 403 # forbidden
            ResponseCode: 200
            ResponsePagePath: "/index.html"
          - ErrorCode: 404 # not found
            ResponseCode: 200
            ResponsePagePath: "/index.html"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 3600 # in seconds
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 86400 # in seconds
          MinTTL: 60 # in seconds
          TargetOriginId: s3origin
          ViewerProtocolPolicy: "allow-all"
        # This DefaultRootObject configuration is not enough.
        DefaultRootObject: "/index.html"
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt "S3Bucket.DomainName"
            Id: s3origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        PriceClass: "PriceClass_All"