name: App CI
on:
  push:
    branches:
      - main
    paths:
      - wellness/**
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        working-directory: ./wellness
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install
      - name: Test
        working-directory: ./wellness
        run: npm test
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add staging homepage
        run: |
          sed -i "1s/.*/\{ \"homepage\": \"wellness_timer\", /" ./wellness/package.json
      - name: Generate build
        working-directory: ./wellness
        run: npm run build
        env:
          REACT_APP_BUILD: ${{ github.sha }}
          REACT_APP_MT_EDIT_BUTTONS_ENABLED: ${{ true }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to staging
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: staging
          folder: wellness/build
