name: App CI
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - public/**
      - package.json
  pull_request_target:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/javascript-node:22-bullseye
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Unit Tests
        run: npm test
        env:
          CI: true
      - name: BDD Tests
        run: npm start & wait-on http://localhost:3000 && npx cypress run
        env:
          CI: true
      - name: Set homepage var
        run: |
          if [ ${{ github.event_name }} = "pull_request" ]; then
            echo "homepage=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "homepage=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
      - name: Escape homepage
        run: |
          ESCAPED=$(echo ${{ env.homepage }} | sed 's/\//\\\//g')
          echo "escaped_homepage=${ESCAPED}" >> $GITHUB_ENV
      - name: Add staging homepage
        run: |
          sed -i "1s/.*/\{ \"homepage\": \"builds\/${{ github.ref_type }}\/${{ env.escaped_homepage }}\", /" ./package.json
      - name: Generate build
        run: npm run build
        env:
          VITE_DISABLE_SERVICE_WORKER: ${{ true }}
          VITE_BUILD: ${{ github.sha }}
          VITE_MT_EDIT_BUTTONS_ENABLED: ${{ true }}
      - name: Deploy to staging
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: staging
          folder: build
          target-folder: builds/${{ github.ref_type }}/${{ env.homepage }}
