name: App CI
on:
  push:
    branches:
      - main
    paths:
      - wellness/**
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        working-directory: ./wellness
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install
      - name: Test
        working-directory: ./wellness
        run: npm test
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate build
        working-directory: ./wellness
        run: npm run build
        env:
          REACT_APP_BUILD: ${{ github.sha }}
          REACT_APP_MT_EDIT_BUTTONS_ENABLED: ${{ true }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: wellness-build-${{ github.sha }}
          path: ./wellness/build
  deploy:
    if: github.repository == 'andy-todd-dev/wellness_timer' && (github.ref =='refs/heads/main')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wellness-build-${{ github.sha }}
          path: ./build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: staging
          folder: build
  performance:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: wellness-build-${{ github.sha }}
          path: ./wellness/build
      - name: Run Lighthouse against build
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: ./wellness/lighthouserc
          uploadArtifacts: true
          temporaryPublicStorage: true 
